name: Builder
on:
  push:
    branches:
      - master
jobs:
  Build-Executable:
    runs-on: ubuntu-latest
    container: docker://galacticusorg/buildenv:latest
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server."
      - run: echo "The name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: "Set environmental variables"
        run: |
          echo "GALACTICUS_EXEC_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "GALACTICUS_FCFLAGS+=\ -static" >> $GITHUB_ENV
      - name: Build the code
        run: |
          echo $GALACTICUS_FCFLAGS
          cd $GALACTICUS_EXEC_PATH
          gfortran -v
          make -j2 Galacticus.exe
          file Galacticus.exe
          mv Galacticus.exe galacticus.exe
          md5sum galacticus.exe
          echo done
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./galacticus.exe
          message: Bleeding edge release
          body: This release is updated to match the latest revision to Galacticus (${{ github.sha }}).
      - run: echo "This job's status is ${{ job.status }}."
