name: Builder-MacOS
on:
  push:
    branches:
      - master
jobs:
  Build-Executable:
    runs-on: macos-latest
    concurrency:
      group: buildmacos-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server."
      - run: echo "The name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: "Set environmental variables"
        run: |
          echo "GALACTICUS_EXEC_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "GALACTICUS_FCFLAGS=$GALACTICUS_FCFLAGS -static" >> $GITHUB_ENV
      - name: Install xcode
        run: |
          cd $GALACTICUS_EXEC_PATH
          echo Do nothing - yet.....
	  gcc -E -dM - < /dev/null
      - run: echo "This job's status is ${{ job.status }}."
